matrix:
  include:
    - language: python
      python: "3.6"
      before_install:
        - git clone --depth=50 --branch=development https://github.com/MansMeg/posteriordb.git
      install: pip install tox-travis codecov
      script: tox
      after_success: codecov
    - language: python
      python: "3.7"
      before_install:
        - git clone --depth=50 --branch=development https://github.com/MansMeg/posteriordb.git
      install: pip install tox-travis codecov
      after_success: codecov
      script: tox
    - name: "Linting and generic checks"
      language: python
      python: "3.7"
      install: pip install pre-commit
      script: pre-commit run --all-files --show-diff-on-failure
